# 1. Configuração do PORTAL (e rotas de API)
server {
    listen 80;
    server_name smsregulacao.com.br www.smsregulacao.com.br;

    # 👇 A MÁGICA ACONTECE AQUI 👇
    # Tudo que tiver /api/ na URL vai ser desviado para o Node.js
    location /api/ {
        proxy_pass http://backend:3333; # Sem barra no final para manter o /api no Node
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    # O resto do site (telas) continua indo para o Next.js
    location / {
        proxy_pass http://frontend:3000; 
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}

# 2. (Opcional) Mantemos o subdomínio da API caso você use para integrações futuras
server {
    listen 80;
    server_name api.smsregulacao.com.br;

    location / {
        proxy_pass http://backend:3333;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}